import { StyleSheet } from 'react-native';
import { COLORS } from '../../lib/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  webview: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.bg,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: COLORS.textMuted,
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.bg,
  },
  loadingBadge: {
    position: 'absolute',
    left: '50%',
    marginLeft: -60,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.surface,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 6,
    gap: 6,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    zIndex: 1000,
  },
  loadingBadgeText: {
    fontSize: 12,
    color: COLORS.textMuted,
  },
  counterBadge: {
    position: 'absolute',
    left: 12,
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    zIndex: 1000,
  },
  counterText: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.textSecondary,
  },
  // Filters
  filterRow: {
    position: 'absolute',
    left: 12,
    right: 60,
    flexDirection: 'row',
    gap: 6,
    zIndex: 1000,
  },
  filterBtn: {
    backgroundColor: COLORS.surface,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 7,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  filterBtnActive: {
    backgroundColor: '#10B981',
  },
  filterBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.textSecondary,
  },
  filterBtnTextActive: {
    color: '#FFF',
  },
  // FABs
  fabButton: {
    position: 'absolute',
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.surface,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    zIndex: 1000,
  },
  // Legend
  legendBox: {
    position: 'absolute',
    backgroundColor: COLORS.surface,
    borderRadius: 12,
    padding: 12,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    minWidth: 160,
    zIndex: 1000,
  },
  legendHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  legendTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.textSecondary,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 5,
  },
  legendDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  legendLabel: {
    fontSize: 11,
    color: COLORS.textMuted,
  },
  // Popup (Inline Bottom Sheet - no Modal)
  popupOverlayInline: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'flex-end',
    zIndex: 2000,
  },
  popupOverlayBg: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  popupSheet: {
    backgroundColor: COLORS.surface,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 16,
    paddingTop: 8,
  },
  popupHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#D1D5DB',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 12,
  },
  popupHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  popupHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    flex: 1,
    gap: 12,
  },
  popupColorDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    marginTop: 4,
  },
  popupName: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.text,
  },
  popupAddress: {
    fontSize: 13,
    color: COLORS.textMuted,
    marginTop: 2,
  },
  popupStatus: {
    fontSize: 12,
    color: COLORS.textLight,
    marginTop: 4,
  },
  popupCloseBtn: {
    padding: 4,
  },
  popupContactRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.bg,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 12,
    gap: 6,
  },
  popupContactText: {
    flex: 1,
    fontSize: 13,
    color: COLORS.textSecondary,
  },
  popupCallBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#10B981',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    gap: 4,
  },
  popupCallBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  popupActions: {
    gap: 8,
  },
  actionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: 12,
    gap: 8,
  },
  actionBtnOutline: {
    backgroundColor: '#EFF6FF',
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  actionBtnPrimary: {
    backgroundColor: '#10B981',
  },
  actionBtnSecondary: {
    backgroundColor: COLORS.bg,
  },
  actionBtnText: {
    fontSize: 14,
    fontWeight: '600',
  },
  grayInfoBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 16,
  },
  grayInfoText: {
    fontSize: 13,
    color: COLORS.textLight,
  },
  // Order Data Modal
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  orderDataModal: {
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: 20,
    width: '85%',
    maxWidth: 340,
  },
  orderDataHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  orderDataTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.text,
  },
  orderDataContent: {
    gap: 12,
  },
  orderDataRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  orderDataLabel: {
    fontSize: 14,
    color: COLORS.textMuted,
  },
  orderDataValue: {
    fontSize: 14,
    color: COLORS.text,
    fontWeight: '500',
  },
  orderDataValueBold: {
    fontSize: 16,
    color: '#10B981',
    fontWeight: '700',
  },
  orderDataEmpty: {
    textAlign: 'center',
    color: COLORS.textLight,
    fontSize: 14,
    marginVertical: 20,
  },
});
