import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F3F4F6',
  },
  stepper: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 8,
    backgroundColor: '#FFFFFF',
  },
  stepDot: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#E5E7EB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepDotCompleted: {
    backgroundColor: '#10B981',
  },
  stepDotCurrent: {
    backgroundColor: '#1E40AF',
  },
  stepNumber: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6B7280',
  },
  stepNumberCurrent: {
    color: '#FFFFFF',
  },
  stepLine: {
    flex: 1,
    height: 2,
    backgroundColor: '#E5E7EB',
    marginHorizontal: 4,
  },
  stepLineCompleted: {
    backgroundColor: '#10B981',
  },
  content: {
    flex: 1,
    paddingHorizontal: 12,
  },
  stepContent: {
    flex: 1,
    paddingTop: 12,
  },
  stepTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 12,
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    paddingHorizontal: 12,
    height: 44,
    marginBottom: 10,
  },
  searchInput: {
    flex: 1,
    marginLeft: 10,
    fontSize: 15,
    color: '#1F2937',
  },
  // Product Row Styles (compact list)
  productList: {
    flex: 1,
  },
  productRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 8,
    marginBottom: 4,
  },
  productRowInCart: {
    borderWidth: 1.5,
    borderColor: '#3B82F6',
    backgroundColor: '#F0F4FF',
  },
  productIconWrap: {
    position: 'relative',
    marginRight: 8,
  },
  productIcon: {
    width: 40,
    height: 40,
    borderRadius: 6,
    backgroundColor: '#F3F4F6',
  },
  productIconPlaceholder: {
    width: 40,
    height: 40,
    borderRadius: 6,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  rowCartBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: '#3B82F6',
    borderRadius: 9,
    minWidth: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
  },
  rowCartBadgeText: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: '700',
  },
  productRowInfo: {
    flex: 1,
    marginRight: 6,
  },
  productRowName: {
    fontSize: 12,
    fontWeight: '500',
    color: '#1F2937',
  },
  productRowPrice: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1E40AF',
  },
  productRowPriceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  productRowAccisaInline: {
    fontSize: 10,
    color: '#F59E0B',
    fontWeight: '500',
  },
  productRowAccisaWrap: {
    width: 52,
    alignItems: 'center',
    marginRight: 6,
  },
  productRowAccisa: {
    fontSize: 10,
    color: '#F59E0B',
    fontWeight: '500',
  },
  productRowAccisaEmpty: {
    fontSize: 10,
    color: '#D1D5DB',
  },
  stockBadge: {
    backgroundColor: '#ECFDF5',
    borderRadius: 6,
    minWidth: 36,
    paddingHorizontal: 6,
    paddingVertical: 4,
    alignItems: 'center',
    marginRight: 6,
  },
  stockBadgeLow: {
    backgroundColor: '#FEF3C7',
  },
  stockBadgeEmpty: {
    backgroundColor: '#FEE2E2',
  },
  stockBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#059669',
  },
  stockBadgeTextEmpty: {
    color: '#DC2626',
  },
  addOneBtn: {
    backgroundColor: '#1E40AF',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginRight: 4,
    minWidth: 38,
    alignItems: 'center',
  },
  addOneBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  addTenBtn: {
    backgroundColor: '#10B981',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 8,
    minWidth: 38,
    alignItems: 'center',
  },
  addTenBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
  addBtnDisabled: {
    backgroundColor: '#D1D5DB',
    opacity: 0.6,
  },
  addBtnTextDisabled: {
    color: '#9CA3AF',
  },
  // Cart Item Edit Modal Styles
  editCartModal: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    margin: 20,
    maxHeight: '80%',
  },
  editCartHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  editCartTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1F2937',
  },
  editCartProductInfo: {
    flexDirection: 'row',
    backgroundColor: '#F9FAFB',
    borderRadius: 10,
    padding: 12,
    marginBottom: 16,
    gap: 12,
  },
  editCartImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
  },
  editCartImagePlaceholder: {
    width: 60,
    height: 60,
    borderRadius: 8,
    backgroundColor: '#E5E7EB',
    alignItems: 'center',
    justifyContent: 'center',
  },
  editCartDetails: {
    flex: 1,
  },
  editCartName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1F2937',
    marginBottom: 2,
  },
  editCartSku: {
    fontSize: 11,
    color: '#9CA3AF',
    marginBottom: 2,
  },
  editCartQty: {
    fontSize: 12,
    color: '#3B82F6',
    fontWeight: '600',
  },
  editCartStock: {
    fontSize: 11,
    color: '#6B7280',
  },
  editCartSection: {
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    paddingTop: 16,
    marginBottom: 16,
  },
  editCartSectionTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 10,
  },
  editCartPriceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  editCartOriginalLabel: {
    fontSize: 13,
    color: '#6B7280',
  },
  editCartOriginalPrice: {
    fontSize: 14,
    color: '#9CA3AF',
    textDecorationLine: 'line-through',
  },
  editCartPriceInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  editCartPriceLabel: {
    fontSize: 13,
    color: '#1F2937',
    flex: 1,
  },
  editCartPriceInput: {
    borderWidth: 1.5,
    borderColor: '#3B82F6',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 16,
    fontWeight: '700',
    color: '#1E40AF',
    width: 110,
    textAlign: 'center',
  },
  editCartApplyBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1E40AF',
    borderRadius: 8,
    paddingVertical: 10,
    gap: 6,
  },
  editCartApplyText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  editCartDeleteBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#DC2626',
    borderRadius: 8,
    paddingVertical: 10,
    gap: 6,
  },
  editCartDeleteText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#DC2626',
  },
  productRowNameTappable: {
    textDecorationLine: 'underline',
    textDecorationColor: '#3B82F6',
  },
  // Cart Bottom Section
  cartBottomSection: {
    marginTop: 6,
  },
  viewCartBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    gap: 4,
  },
  viewCartBtnText: {
    fontSize: 13,
    color: '#1E40AF',
    fontWeight: '600',
  },
  cartModal: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 16,
    maxHeight: '60%',
    width: '100%',
    position: 'absolute',
    bottom: 0,
  },
  cartModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  cartModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1F2937',
  },
  cartModalList: {
    maxHeight: 300,
  },
  // Conflict Banner Styles
  conflictBanner: {
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FECACA',
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
  },
  conflictBannerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  conflictBannerTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#DC2626',
  },
  conflictBannerText: {
    fontSize: 12,
    color: '#7F1D1D',
    lineHeight: 18,
    marginBottom: 8,
  },
  conflictViewCartBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    alignSelf: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#DC2626',
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  conflictViewCartText: {
    fontSize: 12,
    color: '#DC2626',
    fontWeight: '600',
  },
  // Incompatible cart item styles
  cartItemIncompatible: {
    borderWidth: 1.5,
    borderColor: '#EF4444',
    backgroundColor: '#FEF2F2',
  },
  incompatibleBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EF4444',
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
    gap: 4,
    marginBottom: 6,
  },
  incompatibleBadgeText: {
    fontSize: 10,
    color: '#FFFFFF',
    fontWeight: '600',
    flex: 1,
  },
  incompatibleRemoveBtn: {
    backgroundColor: '#FFFFFF',
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  incompatibleRemoveText: {
    fontSize: 10,
    color: '#EF4444',
    fontWeight: '700',
  },
  // CashBack Banner (Step 2)
  cashbackBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#ECFDF5',
    borderWidth: 1.5,
    borderColor: '#10B981',
    borderRadius: 10,
    padding: 12,
    marginTop: 8,
  },
  cashbackBannerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  cashbackBannerTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#065F46',
  },
  cashbackBannerSub: {
    fontSize: 10,
    color: '#047857',
  },
  cashbackBannerBadge: {
    backgroundColor: '#10B981',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  cashbackBannerAmount: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  // CashBack Section (Step 5)
  cashbackHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  cashbackHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  cashbackHeaderTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#065F46',
  },
  cashbackSaldoBadge: {
    backgroundColor: '#10B981',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  cashbackSaldoText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  cashbackEligibleBox: {
    flexDirection: 'row',
    backgroundColor: '#EFF6FF',
    borderRadius: 8,
    padding: 10,
    gap: 8,
    marginBottom: 10,
  },
  cashbackEligibleTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: '#1E40AF',
  },
  cashbackEligibleProducts: {
    fontSize: 11,
    color: '#3B82F6',
    marginTop: 2,
  },
  cashbackInputTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: '#065F46',
    marginBottom: 4,
  },
  cashbackRulesBox: {
    flexDirection: 'row',
    backgroundColor: '#FFFBEB',
    borderRadius: 8,
    padding: 10,
    gap: 6,
    marginTop: 10,
  },
  cashbackRuleNote: {
    fontSize: 10,
    color: '#92400E',
    marginBottom: 6,
    fontStyle: 'italic',
  },
  cashbackRule: {
    fontSize: 10,
    color: '#92400E',
    marginBottom: 2,
  },
  // Rottamazione Section (Step 5)
  rottamazioneHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
  },
  rottamazioneHeaderTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#5B21B6',
  },
  rottamazioneRulesBox: {
    backgroundColor: '#F5F3FF',
    borderRadius: 8,
    padding: 10,
    marginTop: 10,
  },
  rottamazioneRuleText: {
    fontSize: 11,
    color: '#5B21B6',
    marginBottom: 2,
  },
  rottamazioneRuleTextBold: {
    fontSize: 11,
    color: '#5B21B6',
    fontWeight: '700',
    marginBottom: 2,
  },
  rottamazioneRuleTextNote: {
    fontSize: 10,
    color: '#7C3AED',
    fontStyle: 'italic',
    marginTop: 4,
  },
  rottamazioneBadge: {
    backgroundColor: '#F97316',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 3,
    marginLeft: 'auto',
  },
  rottamazioneBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  rottamazioneWarning: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFBEB',
    borderWidth: 1,
    borderColor: '#FCD34D',
    borderRadius: 8,
    padding: 10,
    gap: 6,
    marginTop: 8,
  },
  rottamazioneWarningText: {
    fontSize: 11,
    color: '#92400E',
    flex: 1,
  },
  rottamazioneSummaryBox: {
    backgroundColor: '#FFF7ED',
    borderWidth: 1,
    borderColor: '#FB923C',
    borderRadius: 10,
    padding: 12,
    marginTop: 8,
  },
  rottamazioneSummaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  rottamazioneSummaryLabel: {
    fontSize: 12,
    color: '#9A3412',
    flex: 1,
  },
  rottamazioneSummaryValue: {
    fontSize: 14,
    fontWeight: '700',
    color: '#EA580C',
  },
  rottamazioneSummaryDiscount: {
    fontSize: 14,
    fontWeight: '700',
    color: '#DC2626',
  },
  spreadedPreviewBox: {
    backgroundColor: '#EFF6FF',
    borderWidth: 1,
    borderColor: '#93C5FD',
    borderRadius: 10,
    padding: 12,
    marginTop: 8,
  },
  spreadedPreviewTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1E40AF',
    marginBottom: 6,
  },
  spreadedPreviewItem: {
    fontSize: 11,
    color: '#1E3A8A',
    marginBottom: 2,
  },
  spreadedPreviewItemExcluded: {
    fontSize: 11,
    color: '#DC2626',
    marginBottom: 2,
    textDecorationLine: 'line-through',
    opacity: 0.7,
  },
  // Cart Summary
  cartSummaryCard: {
    backgroundColor: '#1E40AF',
    borderRadius: 10,
    padding: 12,
    marginBottom: 10,
  },
  cartSummaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  cartSummaryLabel: {
    color: '#FFFFFF',
    fontSize: 13,
  },
  cartSummaryTotal: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
  },
  cartSummaryDetails: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 6,
    gap: 8,
  },
  cartDetailText: {
    color: '#93C5FD',
    fontSize: 11,
  },
  // Cart Section
  cartSection: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    padding: 10,
    marginBottom: 10,
    maxHeight: 200,
  },
  sectionLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 8,
  },
  cartItemsList: {
    maxHeight: 160,
  },
  cartItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  cartItemImage: {
    marginRight: 10,
  },
  cartItemImg: {
    width: 40,
    height: 40,
    borderRadius: 6,
  },
  cartItemImgPlaceholder: {
    width: 40,
    height: 40,
    borderRadius: 6,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cartItemDetails: {
    flex: 1,
  },
  cartItemName: {
    fontSize: 13,
    fontWeight: '500',
    color: '#1F2937',
  },
  cartItemPrice: {
    fontSize: 11,
    color: '#6B7280',
  },
  cartItemIva: {
    fontSize: 10,
    color: '#10B981',
  },
  quantityControls: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  quantityBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantityText: {
    fontSize: 14,
    fontWeight: '600',
    marginHorizontal: 10,
    color: '#1F2937',
  },
  // Product Detail Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  productDetailModal: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    width: '100%',
    maxWidth: 350,
  },
  modalClose: {
    position: 'absolute',
    top: 12,
    right: 12,
    zIndex: 1,
  },
  modalImage: {
    width: '100%',
    height: 150,
    borderRadius: 10,
    marginBottom: 12,
  },
  modalImagePlaceholder: {
    width: '100%',
    height: 150,
    borderRadius: 10,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  modalProductName: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1F2937',
    marginBottom: 4,
  },
  modalProductSku: {
    fontSize: 13,
    color: '#6B7280',
    marginBottom: 12,
  },
  modalPriceSection: {
    backgroundColor: '#F9FAFB',
    borderRadius: 10,
    padding: 12,
    marginBottom: 12,
  },
  modalPriceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  modalPriceRowTotal: {
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    paddingTop: 8,
    marginTop: 4,
  },
  modalPriceLabel: {
    fontSize: 13,
    color: '#6B7280',
  },
  modalPriceValue: {
    fontSize: 13,
    color: '#1F2937',
  },
  modalPriceLabelBold: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1F2937',
  },
  modalPriceValueBold: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1E40AF',
  },
  modalBadges: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  modalCashbackBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ECFDF5',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
    gap: 4,
  },
  modalCashbackText: {
    fontSize: 12,
    color: '#10B981',
    fontWeight: '500',
  },
  modalAddBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1E40AF',
    borderRadius: 10,
    padding: 14,
    gap: 8,
  },
  modalAddBtnText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
  },
  // Options (Payment/Shipping)
  optionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    padding: 14,
    marginBottom: 10,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  optionCardSelected: {
    borderColor: '#1E40AF',
    backgroundColor: '#EEF2FF',
  },
  optionInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  optionText: {
    marginLeft: 12,
  },
  optionName: {
    fontSize: 15,
    fontWeight: '500',
    color: '#1F2937',
  },
  optionNameSelected: {
    color: '#1E40AF',
  },
  optionDescription: {
    fontSize: 12,
    color: '#6B7280',
  },
  optionPrice: {
    fontSize: 14,
    fontWeight: '600',
    color: '#10B981',
  },
  // Notes
  notesSection: {
    marginTop: 12,
  },
  textArea: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    padding: 12,
    fontSize: 14,
    color: '#1F2937',
    minHeight: 70,
    textAlignVertical: 'top',
  },
  // Summary
  summarySection: {
    marginBottom: 12,
  },
  summaryLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 6,
  },
  summaryCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    padding: 12,
  },
  summaryValue: {
    fontSize: 14,
    color: '#1F2937',
    marginLeft: 10,
  },
  summaryItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  summaryItemName: {
    fontSize: 13,
    color: '#4B5563',
    flex: 1,
  },
  summaryItemPrice: {
    fontSize: 13,
    fontWeight: '500',
    color: '#1F2937',
  },
  summaryItemLabel: {
    fontSize: 12,
    color: '#6B7280',
  },
  summaryItemValue: {
    fontSize: 12,
    color: '#1F2937',
  },
  summaryDivider: {
    height: 1,
    backgroundColor: '#E5E7EB',
    marginVertical: 8,
  },
  // CashBack
  cashbackCard: {
    borderWidth: 1,
    borderColor: '#10B981',
  },
  cashbackAvailable: {
    fontSize: 14,
    fontWeight: '600',
    color: '#10B981',
    marginBottom: 4,
  },
  cashbackEligible: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 8,
  },
  cashbackNotEligible: {
    fontSize: 12,
    color: '#9CA3AF',
    fontStyle: 'italic',
  },
  cashbackInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  cashbackInputLabel: {
    fontSize: 13,
    color: '#374151',
  },
  cashbackInput: {
    flex: 1,
    backgroundColor: '#F3F4F6',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 14,
  },
  cashbackMaxBtn: {
    backgroundColor: '#10B981',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  cashbackMaxBtnText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  cashbackInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
    gap: 4,
  },
  cashbackInfoText: {
    fontSize: 12,
    color: '#10B981',
    fontWeight: '500',
  },
  // Rottamazione
  rottamazioneCard: {
    borderWidth: 1,
    borderColor: '#8B5CF6',
  },
  rottamazioneInfo: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 8,
  },
  rottamazioneLots: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 8,
  },
  rottamazioneLot: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  rottamazioneLotSelected: {
    backgroundColor: '#8B5CF6',
    borderColor: '#8B5CF6',
  },
  rottamazioneLotText: {
    fontSize: 12,
    color: '#4B5563',
  },
  rottamazioneLotTextSelected: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  rottamazioneNet: {
    fontSize: 12,
    color: '#8B5CF6',
    fontWeight: '500',
    marginBottom: 8,
  },
  rottamazioneInput: {
    backgroundColor: '#F3F4F6',
    borderRadius: 8,
    padding: 10,
    fontSize: 13,
    minHeight: 50,
    textAlignVertical: 'top',
  },
  // Total
  totalSection: {
    backgroundColor: '#1E40AF',
    borderRadius: 12,
    padding: 16,
    marginTop: 12,
    marginBottom: 16,
  },
  discountRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  discountLabel: {
    color: '#93C5FD',
    fontSize: 13,
  },
  discountValue: {
    color: '#FCD34D',
    fontSize: 14,
    fontWeight: '600',
  },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  totalLabel: {
    fontSize: 15,
    color: '#FFFFFF',
  },
  totalAmount: {
    fontSize: 24,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  foreignBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F3E8FF',
    borderRadius: 8,
    padding: 10,
    marginBottom: 16,
  },
  foreignBadgeText: {
    fontSize: 13,
    color: '#8B5CF6',
    marginLeft: 6,
  },
  // Navigation
  navigation: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 12,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  backButtonText: {
    fontSize: 14,
    color: '#6B7280',
    marginLeft: 6,
  },
  nextButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1E40AF',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginLeft: 'auto',
  },
  nextButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
    marginRight: 6,
  },
  submitButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#10B981',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginLeft: 'auto',
  },
  submitButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
    marginLeft: 6,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  // Other
  selectedCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#EEF2FF',
    borderRadius: 10,
    padding: 14,
    marginBottom: 10,
    borderWidth: 2,
    borderColor: '#3B82F6',
  },
  selectedCustomerInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#3B82F6',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  avatarText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  selectedName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1F2937',
  },
  selectedCity: {
    fontSize: 12,
    color: '#6B7280',
  },
  customerList: {
    flex: 1,
  },
  customerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
  },
  customerItemAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#EEF2FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  customerItemAvatarText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#3B82F6',
  },
  customerItemInfo: {
    flex: 1,
    marginLeft: 12,
  },
  customerItemName: {
    fontSize: 14,
    fontWeight: '500',
    color: '#1F2937',
  },
  customerItemCity: {
    fontSize: 12,
    color: '#6B7280',
  },
  productHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  foreignToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E5E7EB',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  foreignToggleActive: {
    backgroundColor: '#8B5CF6',
  },
  foreignToggleText: {
    fontSize: 12,
    color: '#6B7280',
    marginLeft: 4,
  },
  foreignToggleTextActive: {
    color: '#FFFFFF',
  },
  emptyText: {
    textAlign: 'center',
    color: '#9CA3AF',
    marginTop: 24,
    fontSize: 14,
  },
  // Package Toggle Button
  productHeaderBtns: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  packageToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3E8FF',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    gap: 4,
  },
  packageToggleText: {
    fontSize: 12,
    color: '#8B5CF6',
    fontWeight: '600',
  },
  // Package Modal
  packageModal: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 16,
    maxHeight: '80%',
    width: '100%',
    position: 'absolute',
    bottom: 0,
  },
  packageModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  packageModalHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  packageModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1F2937',
  },
  packageSearchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3F4F6',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 12,
    gap: 8,
  },
  packageSearchInput: {
    flex: 1,
    fontSize: 14,
    color: '#1F2937',
    paddingVertical: 0,
  },
  packageLoading: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  packageLoadingText: {
    fontSize: 13,
    color: '#9CA3AF',
    marginTop: 10,
  },
  packageList: {
    flex: 1,
  },
  packageCard: {
    backgroundColor: '#FAFAFA',
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  packageCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  packageCardHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  packageIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#F3E8FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  packageCardName: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1F2937',
  },
  packageCardBranch: {
    fontSize: 11,
    color: '#8B5CF6',
    marginTop: 1,
  },
  packageStatsBadge: {
    backgroundColor: '#EEF2FF',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  packageStatsText: {
    fontSize: 11,
    color: '#4338CA',
    fontWeight: '600',
  },
  packageCardDesc: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 10,
    lineHeight: 18,
  },
  packageItemsList: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 8,
    marginBottom: 10,
  },
  packageItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 4,
    gap: 8,
  },
  packageItemQty: {
    fontSize: 12,
    fontWeight: '700',
    color: '#8B5CF6',
    width: 30,
  },
  packageItemName: {
    fontSize: 12,
    color: '#374151',
    flex: 1,
  },
  packageItemPrice: {
    fontSize: 12,
    fontWeight: '600',
    color: '#1F2937',
  },
  packageMoreItems: {
    fontSize: 11,
    color: '#9CA3AF',
    fontStyle: 'italic',
    marginTop: 4,
    textAlign: 'center',
  },
  packageCardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    paddingTop: 10,
  },
  packageTotalLabel: {
    fontSize: 11,
    color: '#6B7280',
  },
  packageTotalValue: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1F2937',
  },
  packageApplyBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#8B5CF6',
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 6,
  },
  packageApplyText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  packageEmptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  packageEmptyTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#6B7280',
    marginTop: 12,
  },
  packageEmptySubtitle: {
    fontSize: 12,
    color: '#9CA3AF',
    marginTop: 4,
    textAlign: 'center',
  },
});

